//! OpenSKS portable design engine.
//!
//! PR-021 established the `opensks.design-project.v1` bootstrap package contracts
//! plus a deterministic compiler from the platform-neutral token IR to a SwiftUI
//! adapter. PR-037 adds the portable design-*package* registry: discovery in a
//! defined search order, strict path / hash / license / symlink validation
//! (reusing the file-service hardening order), provenance reporting, and legacy
//! `DESIGN.md` normalization. The package wire contracts live in
//! `opensks-contracts::design`; this crate owns the discovery + validation
//! engine. The crate must not depend on the Swift app or the root `opensks`
//! binary.

pub mod contracts;
pub mod registry;

pub use contracts::{
    DESIGN_PROJECT_SCHEMA, DESIGN_TOKEN_SET_SCHEMA, DesignContractError, DesignProjectFiles,
    DesignProjectManifest, DesignSecurity, DesignSource, DesignToken, DesignTokenSet,
};
pub use registry::{
    DesignRegistry, DesignRegistryError, MANIFEST_FILE_NAME, NormalizedDesign, PackageProvenance,
    ResolvedPackage, content_hash, is_valid_package_id, normalize_legacy_design, validate_package,
    validate_relative_file,
};

/// Map a token path (`color.text.primary`, `size.hit_target.primary`) to a
/// camelCase Swift identifier (`colorTextPrimary`, `sizeHitTargetPrimary`).
pub fn swift_identifier(path: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = false;
    let mut started = false;
    for ch in path.chars() {
        if ch == '.' || ch == '_' || ch == '-' {
            capitalize_next = started;
            continue;
        }
        if capitalize_next {
            out.extend(ch.to_uppercase());
            capitalize_next = false;
        } else {
            out.push(ch);
        }
        started = true;
    }
    out
}

fn format_dimension(value: &serde_json::Value) -> String {
    if let Some(n) = value.as_i64() {
        return n.to_string();
    }
    if let Some(n) = value.as_u64() {
        return n.to_string();
    }
    if let Some(n) = value.as_f64() {
        if n.fract() == 0.0 {
            return (n as i64).to_string();
        }
        return n.to_string();
    }
    "0".to_string()
}

/// Compile a token set into a deterministic `GeneratedDesignTokens.swift`
/// source string. Output is stable for a given input (colors then dimensions,
/// each in token order), so the committed file is checked for drift in tests.
pub fn compile_swift_tokens(set: &DesignTokenSet) -> String {
    let mut out = String::new();
    out.push_str("// GeneratedDesignTokens.swift\n");
    out.push_str("// GENERATED by `cargo run -p opensks-design --bin gen-swift-tokens`.\n");
    out.push_str(&format!(
        "// Source of truth: .opensks/design-systems/{}/tokens.json\n",
        set.design_system_id
    ));
    out.push_str(
        "// Do not edit by hand. The opensks-design drift test fails if this file is stale.\n\n",
    );
    out.push_str("import SwiftUI\n\n");
    out.push_str("public enum GeneratedDesignTokens {\n");
    out.push_str(&format!(
        "    public static let revision = {}\n",
        set.revision
    ));

    let colors: Vec<&DesignToken> = set
        .tokens
        .iter()
        .filter(|t| t.token_type == "color")
        .collect();
    if !colors.is_empty() {
        out.push_str("\n    // MARK: Colors\n");
        for token in colors {
            let ident = swift_identifier(&token.path);
            let hex = token
                .value
                .as_str()
                .unwrap_or_default()
                .trim_start_matches('#');
            out.push_str(&format!(
                "    public static let {ident} = Color(hex: \"{hex}\")\n"
            ));
        }
    }

    let dimensions: Vec<&DesignToken> = set
        .tokens
        .iter()
        .filter(|t| t.token_type == "dimension")
        .collect();
    if !dimensions.is_empty() {
        out.push_str("\n    // MARK: Dimensions\n");
        for token in dimensions {
            let ident = swift_identifier(&token.path);
            let number = format_dimension(&token.value);
            out.push_str(&format!(
                "    public static let {ident}: CGFloat = {number}\n"
            ));
        }
    }

    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use opensks_contracts::DesignPackageManifest;
    use std::path::Path;

    const MANIFEST_JSON: &str =
        include_str!("../../../.opensks/design-systems/opensks-studio-dark/manifest.json");
    const TOKENS_JSON: &str =
        include_str!("../../../.opensks/design-systems/opensks-studio-dark/tokens.json");
    const GENERATED_SWIFT: &str =
        include_str!("../../../swift/Sources/DesignSystem/Generated/GeneratedDesignTokens.swift");

    /// Workspace root, two levels above the crate manifest dir.
    fn workspace_root() -> &'static Path {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(Path::parent)
            .expect("workspace root is two levels above the crate manifest")
    }

    #[test]
    fn bundled_manifest_is_valid_package() {
        // Parses as the portable PR-037 package manifest, and the on-disk
        // package passes full strict validation (paths, symlinks, hashes,
        // license) end to end.
        let manifest: DesignPackageManifest =
            serde_json::from_str(MANIFEST_JSON).expect("manifest parses as package");
        assert_eq!(manifest.id, "opensks-studio-dark");
        assert_eq!(manifest.license, "MIT");
        assert!(manifest.platforms.iter().any(|p| p == "macos-swiftui"));

        let package_dir = workspace_root().join(".opensks/design-systems/opensks-studio-dark");
        let validated =
            validate_package("opensks-studio-dark", &package_dir).expect("bundled package valid");
        assert_eq!(validated.id, "opensks-studio-dark");
    }

    #[test]
    fn bundled_package_resolves_local_with_provenance() {
        let registry = DesignRegistry::with_default_order(workspace_root(), None);
        let resolved = registry
            .resolve("opensks-studio-dark")
            .expect("resolve bundled package");
        assert_eq!(resolved.provenance, PackageProvenance::Local);
        let tokens = resolved.load_tokens().expect("load bundled tokens");
        assert_eq!(tokens.design_system_id, "opensks-studio-dark");
        let components = resolved.load_components().expect("load bundled components");
        assert!(components.is_some());
    }

    #[test]
    fn gitignore_tracks_design_systems_but_ignores_cache_and_import_temp() {
        // The shared design-system packages must stay trackable while the design
        // cache and import-temp scratch are ignored. `git check-ignore` exits 0
        // when a path IS ignored and 1 when it is not.
        let root = workspace_root();
        let check_ignored = |path: &str| -> bool {
            std::process::Command::new("git")
                .current_dir(root)
                .args(["check-ignore", "-q", path])
                .status()
                .map(|status| status.success())
                .unwrap_or_else(|_| panic!("run git check-ignore for {path}"))
        };

        // Skip gracefully if git is unavailable or this is not a work tree.
        let in_git = std::process::Command::new("git")
            .current_dir(root)
            .args(["rev-parse", "--is-inside-work-tree"])
            .output()
            .map(|out| out.status.success())
            .unwrap_or(false);
        if !in_git {
            return;
        }

        assert!(
            !check_ignored(".opensks/design-systems/opensks-studio-dark/manifest.json"),
            "bundled design-system package must NOT be gitignored"
        );
        assert!(
            check_ignored(".opensks/design-cache/compiled-adapter.swift"),
            "design cache must be gitignored"
        );
        assert!(
            check_ignored("crates/opensks-design/theme.import-tmp"),
            "*.import-tmp scratch must be gitignored"
        );
    }

    #[test]
    fn bundled_token_set_is_valid_and_bound() {
        let manifest: DesignPackageManifest = serde_json::from_str(MANIFEST_JSON).unwrap();
        let set: DesignTokenSet = serde_json::from_str(TOKENS_JSON).expect("tokens parse");
        set.validate(&manifest.id)
            .expect("token set valid and bound to manifest");
        for required in [
            "color.canvas",
            "color.text.primary",
            "color.accent.primary",
            "size.hit_target.primary",
        ] {
            assert!(
                set.tokens.iter().any(|t| t.path == required),
                "missing required token {required}"
            );
        }
    }

    #[test]
    fn generated_swift_matches_token_set() {
        let set: DesignTokenSet = serde_json::from_str(TOKENS_JSON).unwrap();
        let compiled = compile_swift_tokens(&set);
        assert_eq!(
            compiled, GENERATED_SWIFT,
            "GeneratedDesignTokens.swift is stale; regenerate with `cargo run -p opensks-design --bin gen-swift-tokens`"
        );
    }

    #[test]
    fn swift_identifier_camel_cases_paths() {
        assert_eq!(swift_identifier("color.canvas"), "colorCanvas");
        assert_eq!(swift_identifier("color.text.primary"), "colorTextPrimary");
        assert_eq!(
            swift_identifier("size.hit_target.primary"),
            "sizeHitTargetPrimary"
        );
    }

    #[test]
    fn token_set_rejects_wrong_schema() {
        let bad = DesignTokenSet {
            schema: "wrong".to_string(),
            design_system_id: "opensks-studio-dark".to_string(),
            revision: 1,
            tokens: vec![],
        };
        assert!(bad.validate("opensks-studio-dark").is_err());
    }
}
