//! OpenSKS portable design engine — PR-021 bootstrap.
//!
//! This crate owns the `opensks.design-project.v1` portable package contracts
//! and a deterministic compiler from the platform-neutral token IR to a SwiftUI
//! adapter. It is intentionally minimal; the full registry / import / audit
//! Design Studio arrives in PR-037+. The crate must not depend on the Swift app
//! or the root `opensks` binary.

pub mod contracts;

pub use contracts::{
    DESIGN_PROJECT_SCHEMA, DESIGN_TOKEN_SET_SCHEMA, DesignContractError, DesignProjectFiles,
    DesignProjectManifest, DesignSecurity, DesignSource, DesignToken, DesignTokenSet,
};

/// Map a token path (`color.text.primary`, `size.hit_target.primary`) to a
/// camelCase Swift identifier (`colorTextPrimary`, `sizeHitTargetPrimary`).
pub fn swift_identifier(path: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = false;
    let mut started = false;
    for ch in path.chars() {
        if ch == '.' || ch == '_' || ch == '-' {
            capitalize_next = started;
            continue;
        }
        if capitalize_next {
            out.extend(ch.to_uppercase());
            capitalize_next = false;
        } else {
            out.push(ch);
        }
        started = true;
    }
    out
}

fn format_dimension(value: &serde_json::Value) -> String {
    if let Some(n) = value.as_i64() {
        return n.to_string();
    }
    if let Some(n) = value.as_u64() {
        return n.to_string();
    }
    if let Some(n) = value.as_f64() {
        if n.fract() == 0.0 {
            return (n as i64).to_string();
        }
        return n.to_string();
    }
    "0".to_string()
}

/// Compile a token set into a deterministic `GeneratedDesignTokens.swift`
/// source string. Output is stable for a given input (colors then dimensions,
/// each in token order), so the committed file is checked for drift in tests.
pub fn compile_swift_tokens(set: &DesignTokenSet) -> String {
    let mut out = String::new();
    out.push_str("// GeneratedDesignTokens.swift\n");
    out.push_str("// GENERATED by `cargo run -p opensks-design --bin gen-swift-tokens`.\n");
    out.push_str(&format!(
        "// Source of truth: .opensks/design-systems/{}/tokens.json\n",
        set.design_system_id
    ));
    out.push_str(
        "// Do not edit by hand. The opensks-design drift test fails if this file is stale.\n\n",
    );
    out.push_str("import SwiftUI\n\n");
    out.push_str("public enum GeneratedDesignTokens {\n");
    out.push_str(&format!(
        "    public static let revision = {}\n",
        set.revision
    ));

    let colors: Vec<&DesignToken> = set
        .tokens
        .iter()
        .filter(|t| t.token_type == "color")
        .collect();
    if !colors.is_empty() {
        out.push_str("\n    // MARK: Colors\n");
        for token in colors {
            let ident = swift_identifier(&token.path);
            let hex = token
                .value
                .as_str()
                .unwrap_or_default()
                .trim_start_matches('#');
            out.push_str(&format!(
                "    public static let {ident} = Color(hex: \"{hex}\")\n"
            ));
        }
    }

    let dimensions: Vec<&DesignToken> = set
        .tokens
        .iter()
        .filter(|t| t.token_type == "dimension")
        .collect();
    if !dimensions.is_empty() {
        out.push_str("\n    // MARK: Dimensions\n");
        for token in dimensions {
            let ident = swift_identifier(&token.path);
            let number = format_dimension(&token.value);
            out.push_str(&format!(
                "    public static let {ident}: CGFloat = {number}\n"
            ));
        }
    }

    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    const MANIFEST_JSON: &str =
        include_str!("../../../.opensks/design-systems/opensks-studio-dark/manifest.json");
    const TOKENS_JSON: &str =
        include_str!("../../../.opensks/design-systems/opensks-studio-dark/tokens.json");
    const GENERATED_SWIFT: &str =
        include_str!("../../../swift/Sources/DesignSystem/Generated/GeneratedDesignTokens.swift");

    #[test]
    fn bundled_manifest_is_valid() {
        let manifest: DesignProjectManifest =
            serde_json::from_str(MANIFEST_JSON).expect("manifest parses");
        manifest.validate().expect("manifest schema valid");
        assert_eq!(manifest.id, "opensks-studio-dark");
        assert!(manifest.platforms.iter().any(|p| p == "macos-swiftui"));
    }

    #[test]
    fn bundled_token_set_is_valid_and_bound() {
        let manifest: DesignProjectManifest = serde_json::from_str(MANIFEST_JSON).unwrap();
        let set: DesignTokenSet = serde_json::from_str(TOKENS_JSON).expect("tokens parse");
        set.validate(&manifest.id)
            .expect("token set valid and bound to manifest");
        for required in [
            "color.canvas",
            "color.text.primary",
            "color.accent.primary",
            "size.hit_target.primary",
        ] {
            assert!(
                set.tokens.iter().any(|t| t.path == required),
                "missing required token {required}"
            );
        }
    }

    #[test]
    fn generated_swift_matches_token_set() {
        let set: DesignTokenSet = serde_json::from_str(TOKENS_JSON).unwrap();
        let compiled = compile_swift_tokens(&set);
        assert_eq!(
            compiled, GENERATED_SWIFT,
            "GeneratedDesignTokens.swift is stale; regenerate with `cargo run -p opensks-design --bin gen-swift-tokens`"
        );
    }

    #[test]
    fn swift_identifier_camel_cases_paths() {
        assert_eq!(swift_identifier("color.canvas"), "colorCanvas");
        assert_eq!(swift_identifier("color.text.primary"), "colorTextPrimary");
        assert_eq!(
            swift_identifier("size.hit_target.primary"),
            "sizeHitTargetPrimary"
        );
    }

    #[test]
    fn token_set_rejects_wrong_schema() {
        let bad = DesignTokenSet {
            schema: "wrong".to_string(),
            design_system_id: "opensks-studio-dark".to_string(),
            revision: 1,
            tokens: vec![],
        };
        assert!(bad.validate("opensks-studio-dark").is_err());
    }
}
