//! OpenSKS portable design engine.
//!
//! PR-021 established the `opensks.design-project.v1` bootstrap package contracts
//! plus a deterministic compiler from the platform-neutral token IR to a SwiftUI
//! adapter. PR-037 adds the portable design-*package* registry: discovery in a
//! defined search order, strict path / hash / license / symlink validation
//! (reusing the file-service hardening order), provenance reporting, and legacy
//! `DESIGN.md` normalization. The package wire contracts live in
//! `opensks-contracts::design`; this crate owns the discovery + validation
//! engine. The crate must not depend on the Swift app or the root `opensks`
//! binary.

pub mod activation;
pub mod audit;
pub mod compiler;
pub mod contracts;
pub mod import;
pub mod registry;
pub mod revision;

pub use activation::{
    ActivationError, ActivationOutcome, ActiveMarker, DESIGN_ACTIVE_SCHEMA, activate_package,
    read_active,
};
pub use audit::{
    DESIGN_AUDIT_SCHEMA, DesignAuditError, DesignAuditReport, DesignFinding, FindingKind, Severity,
    audit_package, contrast_ratio,
};
pub use compiler::{
    DesignCompileError, DesignContext, ResolvedTokenSet, build_design_context_pack,
    compile_css_tokens, pin_design_context, resolve_token_set, verify_design_context_pin,
};
pub use contracts::{
    DESIGN_PROJECT_SCHEMA, DESIGN_TOKEN_SET_SCHEMA, DesignContractError, DesignProjectFiles,
    DesignProjectManifest, DesignSecurity, DesignSource, DesignToken, DesignTokenSet,
};
pub use import::{
    ApproveOutcome, ImportError, ImportKind, ImportLimits, ImportOutcome, Provenance,
    QuarantineEntry, QuarantineStatus, RejectedReason, approve_import, list_quarantines,
    quarantine_import, reject_import, render_status_json,
};
pub use registry::{
    DesignRegistry, DesignRegistryError, MANIFEST_FILE_NAME, NormalizedDesign, PackageProvenance,
    ResolvedPackage, content_hash, is_valid_package_id, normalize_legacy_design, validate_package,
    validate_relative_file,
};
pub use revision::{
    DESIGN_REVISION_SCHEMA, Revision, RevisionError, RevisionState, accept_revision, load_revision,
    propose_revision, reject_revision, rollback_revision,
};

/// Map a token path (`color.text.primary`, `size.hit_target.primary`) to a
/// camelCase Swift identifier (`colorTextPrimary`, `sizeHitTargetPrimary`).
pub fn swift_identifier(path: &str) -> String {
    let mut out = String::new();
    let mut capitalize_next = false;
    let mut started = false;
    for ch in path.chars() {
        if ch == '.' || ch == '_' || ch == '-' {
            capitalize_next = started;
            continue;
        }
        if capitalize_next {
            out.extend(ch.to_uppercase());
            capitalize_next = false;
        } else {
            out.push(ch);
        }
        started = true;
    }
    out
}

fn format_dimension(value: &serde_json::Value) -> String {
    if let Some(n) = value.as_i64() {
        return n.to_string();
    }
    if let Some(n) = value.as_u64() {
        return n.to_string();
    }
    if let Some(n) = value.as_f64() {
        if n.fract() == 0.0 {
            return (n as i64).to_string();
        }
        return n.to_string();
    }
    "0".to_string()
}

/// Compile a token set into a deterministic `GeneratedDesignTokens.swift`
/// source string. Aliases are resolved to concrete values first (see
/// [`compile_swift_tokens_checked`] for the strict, error-returning path); a set
/// that fails resolution falls back to its raw tokens so this infallible entry
/// point never panics. Output is stable for a given input (colors then
/// dimensions, each in token order), so the committed file is checked for drift.
pub fn compile_swift_tokens(set: &DesignTokenSet) -> String {
    match resolve_token_set(set) {
        Ok(resolved) => compile_swift_tokens_resolved(&resolved),
        Err(_) => compile_swift_tokens_resolved(&ResolvedTokenSet {
            design_system_id: set.design_system_id.clone(),
            revision: set.revision,
            tokens: set.tokens.clone(),
        }),
    }
}

/// Resolve aliases, then compile the resolved set into the Swift adapter.
/// Surfaces a typed [`DesignCompileError`] on a cyclic, unresolved, or
/// type-mismatched alias instead of silently degrading.
pub fn compile_swift_tokens_checked(set: &DesignTokenSet) -> Result<String, DesignCompileError> {
    let resolved = resolve_token_set(set)?;
    Ok(compile_swift_tokens_resolved(&resolved))
}

/// Compile a *resolved* token set into the deterministic Swift adapter. Token
/// order is preserved (colors in token order, then dimensions in token order),
/// so for an alias-free set this is byte-identical to the committed file.
pub fn compile_swift_tokens_resolved(set: &ResolvedTokenSet) -> String {
    let mut out = String::new();
    out.push_str("// GeneratedDesignTokens.swift\n");
    out.push_str("// GENERATED by `cargo run -p opensks-design --bin gen-swift-tokens`.\n");
    out.push_str(&format!(
        "// Source of truth: .opensks/design-systems/{}/tokens.json\n",
        set.design_system_id
    ));
    out.push_str(
        "// Do not edit by hand. The opensks-design drift test fails if this file is stale.\n\n",
    );
    out.push_str("import SwiftUI\n\n");
    out.push_str("public enum GeneratedDesignTokens {\n");
    out.push_str(&format!(
        "    public static let revision = {}\n",
        set.revision
    ));

    let colors: Vec<&DesignToken> = set
        .tokens
        .iter()
        .filter(|t| t.token_type == "color")
        .collect();
    if !colors.is_empty() {
        out.push_str("\n    // MARK: Colors\n");
        for token in colors {
            let ident = swift_identifier(&token.path);
            let hex = token
                .value
                .as_str()
                .unwrap_or_default()
                .trim_start_matches('#');
            out.push_str(&format!(
                "    public static let {ident} = Color(hex: \"{hex}\")\n"
            ));
        }
    }

    let dimensions: Vec<&DesignToken> = set
        .tokens
        .iter()
        .filter(|t| t.token_type == "dimension")
        .collect();
    if !dimensions.is_empty() {
        out.push_str("\n    // MARK: Dimensions\n");
        for token in dimensions {
            let ident = swift_identifier(&token.path);
            let number = format_dimension(&token.value);
            out.push_str(&format!(
                "    public static let {ident}: CGFloat = {number}\n"
            ));
        }
    }

    out.push_str("}\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use opensks_contracts::{DesignPackageComponents, DesignPackageManifest};
    use std::path::Path;

    const MANIFEST_JSON: &str =
        include_str!("../../../.opensks/design-systems/opensks-studio-dark/manifest.json");
    const TOKENS_JSON: &str =
        include_str!("../../../.opensks/design-systems/opensks-studio-dark/tokens.json");
    const GENERATED_SWIFT: &str =
        include_str!("../../../swift/Sources/DesignSystem/Generated/GeneratedDesignTokens.swift");

    /// Workspace root, two levels above the crate manifest dir.
    fn workspace_root() -> &'static Path {
        Path::new(env!("CARGO_MANIFEST_DIR"))
            .parent()
            .and_then(Path::parent)
            .expect("workspace root is two levels above the crate manifest")
    }

    #[test]
    fn bundled_manifest_is_valid_package() {
        // Parses as the portable PR-037 package manifest, and the on-disk
        // package passes full strict validation (paths, symlinks, hashes,
        // license) end to end.
        let manifest: DesignPackageManifest =
            serde_json::from_str(MANIFEST_JSON).expect("manifest parses as package");
        assert_eq!(manifest.id, "opensks-studio-dark");
        assert_eq!(manifest.license, "MIT");
        assert!(manifest.platforms.iter().any(|p| p == "macos-swiftui"));

        let package_dir = workspace_root().join(".opensks/design-systems/opensks-studio-dark");
        let validated =
            validate_package("opensks-studio-dark", &package_dir).expect("bundled package valid");
        assert_eq!(validated.id, "opensks-studio-dark");
    }

    #[test]
    fn bundled_package_resolves_local_with_provenance() {
        let registry = DesignRegistry::with_default_order(workspace_root(), None);
        let resolved = registry
            .resolve("opensks-studio-dark")
            .expect("resolve bundled package");
        assert_eq!(resolved.provenance, PackageProvenance::Local);
        let tokens = resolved.load_tokens().expect("load bundled tokens");
        assert_eq!(tokens.design_system_id, "opensks-studio-dark");
        let components = resolved.load_components().expect("load bundled components");
        assert!(components.is_some());
    }

    #[test]
    fn gitignore_tracks_design_systems_but_ignores_cache_and_import_temp() {
        // The shared design-system packages must stay trackable while the design
        // cache and import-temp scratch are ignored. `git check-ignore` exits 0
        // when a path IS ignored and 1 when it is not.
        let root = workspace_root();
        let check_ignored = |path: &str| -> bool {
            std::process::Command::new("git")
                .current_dir(root)
                .args(["check-ignore", "-q", path])
                .status()
                .map(|status| status.success())
                .unwrap_or_else(|_| panic!("run git check-ignore for {path}"))
        };

        // Skip gracefully if git is unavailable or this is not a work tree.
        let in_git = std::process::Command::new("git")
            .current_dir(root)
            .args(["rev-parse", "--is-inside-work-tree"])
            .output()
            .map(|out| out.status.success())
            .unwrap_or(false);
        if !in_git {
            return;
        }

        assert!(
            !check_ignored(".opensks/design-systems/opensks-studio-dark/manifest.json"),
            "bundled design-system package must NOT be gitignored"
        );
        assert!(
            check_ignored(".opensks/design-cache/compiled-adapter.swift"),
            "design cache must be gitignored"
        );
        assert!(
            check_ignored("crates/opensks-design/theme.import-tmp"),
            "*.import-tmp scratch must be gitignored"
        );
    }

    #[test]
    fn bundled_token_set_is_valid_and_bound() {
        let manifest: DesignPackageManifest = serde_json::from_str(MANIFEST_JSON).unwrap();
        let set: DesignTokenSet = serde_json::from_str(TOKENS_JSON).expect("tokens parse");
        set.validate(&manifest.id)
            .expect("token set valid and bound to manifest");
        for required in [
            "color.canvas",
            "color.text.primary",
            "color.accent.primary",
            "size.hit_target.primary",
        ] {
            assert!(
                set.tokens.iter().any(|t| t.path == required),
                "missing required token {required}"
            );
        }
    }

    #[test]
    fn generated_swift_matches_token_set() {
        let set: DesignTokenSet = serde_json::from_str(TOKENS_JSON).unwrap();
        let compiled = compile_swift_tokens(&set);
        assert_eq!(
            compiled, GENERATED_SWIFT,
            "GeneratedDesignTokens.swift is stale; regenerate with `cargo run -p opensks-design --bin gen-swift-tokens`"
        );
    }

    #[test]
    fn swift_identifier_camel_cases_paths() {
        assert_eq!(swift_identifier("color.canvas"), "colorCanvas");
        assert_eq!(swift_identifier("color.text.primary"), "colorTextPrimary");
        assert_eq!(
            swift_identifier("size.hit_target.primary"),
            "sizeHitTargetPrimary"
        );
    }

    #[test]
    fn token_set_rejects_wrong_schema() {
        let bad = DesignTokenSet {
            schema: "wrong".to_string(),
            design_system_id: "opensks-studio-dark".to_string(),
            revision: 1,
            tokens: vec![],
        };
        assert!(bad.validate("opensks-studio-dark").is_err());
    }

    // ---- PR-038: compiler determinism, alias resolution, context packs ----

    fn token(path: &str, ty: &str, value: serde_json::Value) -> DesignToken {
        DesignToken {
            path: path.to_string(),
            token_type: ty.to_string(),
            value,
            unit: if ty == "dimension" {
                Some("pt".to_string())
            } else {
                None
            },
            semantic_role: None,
            confidence: None,
            source_refs: vec![],
            contrast_constraints: vec![],
        }
    }

    fn set_with(tokens: Vec<DesignToken>) -> DesignTokenSet {
        DesignTokenSet {
            schema: DESIGN_TOKEN_SET_SCHEMA.to_string(),
            design_system_id: "demo".to_string(),
            revision: 1,
            tokens,
        }
    }

    fn bundled_set() -> DesignTokenSet {
        serde_json::from_str(TOKENS_JSON).expect("bundled tokens parse")
    }

    #[test]
    fn swift_and_css_compilation_is_byte_identical_across_runs() {
        // DETERMINISM: compiling the bundled sample token set twice yields
        // identical Swift and identical CSS bytes (no HashMap order, no clock).
        let set = bundled_set();
        let resolved = resolve_token_set(&set).expect("bundled set resolves");

        let swift_a = compile_swift_tokens(&set);
        let swift_b = compile_swift_tokens(&set);
        assert_eq!(swift_a, swift_b, "Swift output is not deterministic");

        let css_a = compile_css_tokens(&resolved);
        let css_b = compile_css_tokens(&resolved);
        assert_eq!(css_a, css_b, "CSS output is not deterministic");

        // The CSS adapter sorts custom properties by token path.
        assert!(css_a.contains("--color-accent-primary: #5EDEC4;"));
        assert!(css_a.contains("--size-hit-target-primary: 44px;"));
        let accent = css_a.find("--color-accent-primary").unwrap();
        let canvas = css_a.find("--color-canvas").unwrap();
        assert!(accent < canvas, "CSS properties must be sorted by path");
    }

    #[test]
    fn alias_chain_resolves_to_concrete_value() {
        // a -> b -> #5EDEC4 resolves both `a` and `b` to the concrete hex.
        let set = set_with(vec![
            token("color.a", "color", serde_json::json!("{color.b}")),
            token("color.b", "color", serde_json::json!("{color.brand}")),
            token("color.brand", "color", serde_json::json!("#5EDEC4")),
        ]);
        let resolved = resolve_token_set(&set).expect("alias chain resolves");
        assert_eq!(
            resolved.get("color.a").unwrap().value,
            serde_json::json!("#5EDEC4")
        );
        assert_eq!(
            resolved.get("color.b").unwrap().value,
            serde_json::json!("#5EDEC4")
        );
    }

    #[test]
    fn cyclic_alias_is_rejected() {
        // a -> b -> a is a cycle.
        let set = set_with(vec![
            token("color.a", "color", serde_json::json!("{color.b}")),
            token("color.b", "color", serde_json::json!("{color.a}")),
        ]);
        let error = resolve_token_set(&set).expect_err("cycle rejected");
        assert_eq!(error.reason_code(), "design_alias_cycle");
        assert!(matches!(error, DesignCompileError::AliasCycle { .. }));
    }

    #[test]
    fn unresolved_alias_is_rejected() {
        let set = set_with(vec![token(
            "color.a",
            "color",
            serde_json::json!("{color.missing}"),
        )]);
        let error = resolve_token_set(&set).expect_err("unresolved rejected");
        assert_eq!(error.reason_code(), "design_alias_unresolved");
    }

    #[test]
    fn type_mismatched_alias_is_rejected() {
        // A color token aliasing a dimension/number is a type error.
        let set = set_with(vec![
            token("color.a", "color", serde_json::json!("{size.gap}")),
            token("size.gap", "dimension", serde_json::json!(8)),
        ]);
        let error = resolve_token_set(&set).expect_err("type mismatch rejected");
        assert_eq!(error.reason_code(), "design_alias_type_mismatch");
        assert!(matches!(
            error,
            DesignCompileError::AliasTypeMismatch { .. }
        ));
    }

    #[test]
    fn checked_swift_surfaces_alias_errors() {
        let set = set_with(vec![
            token("color.a", "color", serde_json::json!("{color.b}")),
            token("color.b", "color", serde_json::json!("{color.a}")),
        ]);
        assert!(compile_swift_tokens_checked(&set).is_err());
    }

    #[test]
    fn swift_compiles_alias_to_resolved_value() {
        // An aliasing set compiles to the concrete target's hex in Swift.
        let set = set_with(vec![
            token("color.brand", "color", serde_json::json!("#5EDEC4")),
            token("color.accent", "color", serde_json::json!("{color.brand}")),
        ]);
        let swift = compile_swift_tokens(&set);
        assert!(swift.contains("colorAccent = Color(hex: \"5EDEC4\")"));
    }

    #[test]
    fn context_pack_selects_only_relevant_within_budget_and_is_deterministic() {
        // A set with tokens relevant to "color" and irrelevant ones (spacing).
        let set = bundled_set();
        let resolved = resolve_token_set(&set).expect("resolves");
        let components = DesignPackageComponents {
            schema: "opensks.component-catalog.v1".to_string(),
            design_system_id: "demo".to_string(),
            components: vec![],
        };
        let context = compiler::DesignContext::new(&resolved).with_components(&components);

        let pack = build_design_context_pack(&context, "color accent", 3, 100_000);
        // Only color tokens selected — no dimension/spacing tokens.
        assert!(!pack.items.is_empty());
        assert!(
            pack.items
                .iter()
                .all(|item| item.reference.starts_with("color.")),
            "irrelevant (non-color) items must be excluded"
        );
        // Item budget respected.
        assert!(pack.items.len() <= 3);
        // Char budget respected.
        assert!(pack.total_chars <= 100_000);
        // Body matches the selected item texts joined by newline.
        let expected_body = pack
            .items
            .iter()
            .map(|i| i.text.clone())
            .collect::<Vec<_>>()
            .join("\n");
        assert_eq!(pack.body, expected_body);

        // Same query + budget -> identical pack (byte-identical JSON).
        let pack_again = build_design_context_pack(&context, "color accent", 3, 100_000);
        assert_eq!(pack, pack_again);
        let json_a = serde_json::to_string(&pack).unwrap();
        let json_b = serde_json::to_string(&pack_again).unwrap();
        assert_eq!(json_a, json_b);
    }

    #[test]
    fn context_pack_char_budget_excludes_over_budget_items() {
        let set = bundled_set();
        let resolved = resolve_token_set(&set).expect("resolves");
        let context = compiler::DesignContext::new(&resolved);
        // A tiny char budget admits at most one short line.
        let pack = build_design_context_pack(&context, "color", 50, 40);
        assert!(pack.total_chars <= 40);
        // Every admitted item individually fit.
        assert!(pack.items.iter().all(|item| item.char_cost <= 40));
    }

    #[test]
    fn context_pin_is_stable_and_verifiable() {
        let set = bundled_set();
        let resolved = resolve_token_set(&set).expect("resolves");
        let context = compiler::DesignContext::new(&resolved);
        let pack = build_design_context_pack(&context, "color", 3, 100_000);

        let pin_a = pin_design_context(&pack, "model-x", "rev-7");
        let pin_b = pin_design_context(&pack, "model-x", "rev-7");
        assert_eq!(pin_a, pin_b, "pin must be deterministic");
        assert!(verify_design_context_pin(&pin_a, &pack, "model-x", "rev-7"));
        // A different model id or revision fails verification.
        assert!(!verify_design_context_pin(
            &pin_a, &pack, "model-y", "rev-7"
        ));
        assert!(!verify_design_context_pin(
            &pin_a, &pack, "model-x", "rev-8"
        ));
    }
}
